<?php


namespace App\Controllers;


use flowerphp\App;

class BaseController extends Controller
{
    public function request(App $app)
    {
        parent::request($app); // TODO: Change the autogenerated stub
        return $this->returnMeText();
    }

    protected function returnMeText()
    {
        return 'OK';
    }
}